fix: resolve connection issue potentially
Signed-off-by: Anatoli Nicolae <an@thundersquared.com>

diff --git a/.github/workflows/web8-ansible-deploy.yml b/.github/workflows/web8-ansible-deploy.yml
--- a/.github/workflows/web8-ansible-deploy.yml
+++ b/.github/workflows/web8-ansible-deploy.yml
@@ -14,13 +14,15 @@ jobs:
           version: "11.8.0"
       - name: Set up inventory with secrets and SSH key
         run: |
-          echo "TARGET_HOST=${{ secrets.HOST }}" >> $GITHUB_ENV
-          echo "ANSIBLE_USER=${{ secrets.USER }}" >> $GITHUB_ENV
+          if [ -z "${{ secrets.HOST }}" ] || [ -z "${{ secrets.USER }}" ]; then
+            echo "HOST or USER secret is missing!" >&2
+            exit 1
+          fi
           mkdir -p ~/.ssh
           chmod 700 ~/.ssh
           echo "${{ secrets.SSH_PRIVATE_KEY }}" | base64 --decode > ~/.ssh/id_ed25519
           chmod 600 ~/.ssh/id_ed25519
-          echo "$TARGET_HOST ansible_user=$ANSIBLE_USER ansible_ssh_private_key=~/.ssh/id_ed25519" > inventory
+          echo "${{ secrets.HOST }} ansible_user=${{ secrets.USER }} ansible_ssh_private_key=~/.ssh/id_ed25519" > inventory
       - name: Cache Ansible Galaxy requirements
         uses: actions/cache@v4
         with:
